[package]
name = "manager-rust-test"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winnt", "winuser", "minwindef", "libloaderapi"] }
